### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/UCF-101/train/metadata_16.pkl'

### ISSUE THREAD

**Issue by maguro27** [SongweiGe/TATS#20]
Hi.
Thank you for your great work!
Unfortunately, I got an error when I ran the VQGAN train script.

```
Traceback (most recent call last):
  File "scripts/train_vqgan.py", line 70, in <module>
    main()
  File "scripts/train_vqgan.py", line 21, in main
    data.train_dataloader()
  File "mydir/TATS/scripts/tats/data.py", line 296, in train_dataloader
    return self._dataloader(True)
  File "mydir/TATS/scripts/tats/data.py", line 275, in _dataloader
    dataset = self._dataset(train)
  File "mydir/TATS/scripts/tats/data.py", line 270, in _dataset
    dataset = Dataset(self.args.data_path, self.args.sequence_length,
  File "mydir/TATS/scripts/tats/data.py", line 60, in __init__
    pickle.dump(clips.metadata, open(cache_file, 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/UCF-101/train/metadata_16.pkl'
```

Although I downloaded the UCF-101 dataset from the official website, the UCF-101 folder does not include the `train` folder and `metada_16.pkl`.
How can I preprocess the dataset?
The thrown script is as follows,

```
python scripts/train_vqgan.py \
--embedding_dim 256 \
--n_codes 16384 \
--n_hiddens 32 \
--downsample 4 8 8 \
--no_random_restart \
--gpus 8 \
--sync_batchnorm \
--batch_size 2 \
--num_workers 32 \
--accumulate_grad_batches 6 \
--progress_bar_refresh_rate 500 \
--max_steps 2000000 \
--gradient_clip_val 1.0 \
--lr 3e-5 \
--data_path datasets/UCF-101 \
--default_root_dir ckpt \
--resolution 128 \
--sequence_length 16 \
--discriminator_iter_start 10000 \
--norm_type batch \
--perceptual_weight 4 \
--image_gan_weight 1 \
--video_gan_weight 1 \
--gan_feat_weight 4 
```

Thanks.

**Comment by maguro27** [comment]
I wrote the script.

```
import os
import os.path as osp
import shutil
import argparse
from glob import glob
from progressbar import progressbar


def main(args) -> None:
    org_path = args.data_dir
    dst_dir = org_path + "_split"
    dst_train = osp.join(dst_dir, "train")
    dst_test = osp.join(dst_dir, "test")

    with open(
        osp.join(args.anno_dir, "trainlist{}.txt".format(args.split_anno_num)), "r"
    ) as f:
        train_annos = sorted(f.readlines())
    with open(
        osp.join(args.anno_dir, "testlist{}.txt".format(args.split_anno_num)), "r"
    ) as f:
        test_annos = sorted(f.readlines())

    for train_anno in progressbar(train_annos):
        class_file = train_anno.split(" ")[0]
        class_name = class_file.split("/")[0]
        file_name = class_file.split("/")[1]

        org_file_path = osp.join(org_path, class_file)
        dst_train_class_dir = osp.join(dst_train, class_name)
        os.makedirs(dst_train_class_dir, exist_ok=True)

        shutil.copy2(org_file_path, osp.join(dst_train_class_dir, file_name))

    for test_anno in progressbar(test_annos):
        class_file = test_anno.strip("\n")
        class_name = class_file.split("/")[0]
        file_name = class_file.split("/")[1]

        org_file_path = osp.join(org_path, class_file)
        dst_test_class_dir = osp.join(dst_test, class_name)
        os.makedirs(dst_test_class_dir, exist_ok=True)

        shutil.copy2(org_file_path, osp.join(dst_test_class_dir, file_name))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--data_dir",
        type=str,
        default="datasets/UCF-101",
        help="original dataset directory path",
    )
    parser.add_argument(
        "--anno_dir",
        type=str,
        default="datasets/ucfTrainTestlist",
        help="annotation file directory",
    )
    parser.add_argument(
        "--split_anno_num",
        type=str,
        required=True,
        help="the number of annotation text file of classes, i.e. 01, 02, or 03.",
    )

    args = parser.parse_args()

    main(args)
```

Clothing this issue.
